// Auto-generated shared brand data (logo + live product count), used by every
// standalone product page to render its "Associate Brands" section dynamically.
// This mirrors the same source of truth (products/brands/brandLogos) already
// used by the dynamic homepage brand strip, so the two can never disagree.
// Regenerate this file whenever a product or brand is added.
// NOTE (8 Sep 2026): logos moved from inline base64 to external files under
// images/brands/ -- keeps this file tiny (~2KB vs previously 570KB) since it
// loads on every one of the 127+ standalone product pages. Paths are relative
// to products/*.html (the only place this file is loaded from), hence "../".
// See SEO/GEO standing checklist in RKIC-Site-Reminder-Instructions.md, Section 9.
// NOTE (16 Sep 2026): added "slug" field (matches brands/*.html page filenames,
// generated by tmp/brands_gen/gen_brands.py) so the Associate Brands chip strip
// on every page can link to a real crawlable brands/<slug>.html instead of the
// old index.html#/brand/X hash route.
window.RKIC_BRANDS = [{"name": "Brahma", "logo": "../images/brands/brand-brahma.png", "count": 27, "slug": "brahma"}, {"name": "Cofi", "logo": "../images/brands/brand-cofi.png", "count": 3, "slug": "cofi"}, {"name": "Danfoss", "logo": "../images/brands/brand-danfoss.png", "count": 2, "slug": "danfoss"}, {"name": "Dungs", "logo": "../images/brands/brand-dungs.png", "count": 4, "slug": "dungs"}, {"name": "Elektrogas", "logo": "../images/brands/brand-elektrogas.png", "count": 8, "slug": "elektrogas"}, {"name": "Honeywell Eclipse", "logo": "../images/brands/brand-honeywell-eclipse.png", "count": 1, "slug": "honeywell-eclipse"}, {"name": "Honeywell Elster", "logo": "../images/brands/brand-honeywell-elster.png", "count": 12, "slug": "honeywell-elster"}, {"name": "Honeywell Kromschröder", "logo": "../images/brands/brand-honeywell-kromschroder.png", "count": 14, "slug": "honeywell-kromschroder"}, {"name": "Honeywell Maxon", "logo": "../images/brands/brand-honeywell-maxon.png", "count": 3, "slug": "honeywell-maxon"}, {"name": "Honeywell Technologies", "logo": "../images/brands/brand-honeywell-technologies.png", "count": 12, "slug": "honeywell-technologies"}, {"name": "Madas", "logo": "../images/brands/brand-madas.png", "count": 14, "slug": "madas"}, {"name": "R.K. Instruments & Controls", "logo": "../images/brands/brand-r-k-instruments-and-controls.png", "count": 14, "slug": "r-k-instruments-and-controls"}, {"name": "Siemens", "logo": "../images/brands/brand-siemens.png", "count": 14, "slug": "siemens"}, {"name": "Vanaz", "logo": "../images/brands/brand-vanaz.png", "count": 21, "slug": "vanaz"}];
